### ISSUE TITLE
added this to pm3 client

### ISSUE THREAD

**Issue by iceman1001** [J-Run/mf_key_brute#1]
Hi,
Not an issue but I just wanted to let you know that I'm about to add this part into my fork for pm3.
The command will look like below

`hf mf keybrute 1 A xxxx11223344`

Will test and finish up tonight.

**Comment by iceman1001** [comment]
Looks decent,  I'm estimating 18min to exhaust all 0xFFFF possibilities with online authentications against tag.  How fast is your imp?

**Comment by J-Run** [comment]
Hi iceman!
Thankyou for your attention and porting to pm3.
Looks like your implementaton with pm3 is 3-5 times faster than  this one with libnfc+acr122u!
Great work!

**Comment by iceman1001** [comment]
Question is if there is some need to port the phase 1..
